#' Drive API
#' Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.
#'
#' Auto-generated code by googleAuthR::gar_create_api_skeleton
#'  at 2018-07-26 15:00:26
#' filename: ~/Documents/github/googledrivev3.auto/R/drive_functions.R
#' api_json: api_json
#'
#' @details
#' Authentication scopes used are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/drive
#' \item https://www.googleapis.com/auth/drive.appdata
#' \item https://www.googleapis.com/auth/drive.file
#' \item https://www.googleapis.com/auth/drive.metadata
#' \item https://www.googleapis.com/auth/drive.metadata.readonly
#' \item https://www.googleapis.com/auth/drive.photos.readonly
#' \item https://www.googleapis.com/auth/drive.readonly
#' \item https://www.googleapis.com/auth/drive.scripts
#' }
#'
#' @docType package
#' @name drive_googleAuthR
#'
NULL
## NULL



#' Creates a copy of a file and applies any requested updates with patch semantics.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://developers.google.com/drive/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/drive
#' \item https://www.googleapis.com/auth/drive.appdata
#' \item https://www.googleapis.com/auth/drive.file
#' \item https://www.googleapis.com/auth/drive.photos.readonly
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/drive, https://www.googleapis.com/auth/drive.appdata, https://www.googleapis.com/auth/drive.file, https://www.googleapis.com/auth/drive.photos.readonly)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param File The \link{File} object to pass to this method
#' @param fileId The ID of the file
#' @param ignoreDefaultVisibility Whether to ignore the domain's default visibility settings for the created file
#' @param keepRevisionForever Whether to set the 'keepForever' field in the new head revision
#' @param ocrLanguage A language hint for OCR processing during image import (ISO 639-1 code)
#' @param supportsTeamDrives Whether the requesting application supports Team Drives
#' @importFrom googleAuthR gar_api_generator
#' @family File functions
#' @export
files.copy <- function(File, fileId, ignoreDefaultVisibility = NULL, keepRevisionForever = NULL,
    ocrLanguage = NULL, supportsTeamDrives = NULL) {
    url <- sprintf("https://www.googleapis.com/drive/v3/files/%s/copy", fileId)
    # drive.files.copy
    pars = list(ignoreDefaultVisibility = ignoreDefaultVisibility, keepRevisionForever = keepRevisionForever,
        ocrLanguage = ocrLanguage, supportsTeamDrives = supportsTeamDrives)
    f <- googleAuthR::gar_api_generator(url, "POST", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    stopifnot(inherits(File, "gar_File"))

    f(the_body = File)

}



