#' Drive API Objects
#' Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.
#'
#' Auto-generated code by googleAuthR::gar_create_api_objects
#'  at 2018-07-26 15:00:27
#' filename: ~/Documents/github/googledrivev3.auto/R/drive_objects.R
#' api_json: api_json
#'
#' Objects for use by the functions created by googleAuthR::gar_create_api_skeleton

#' File Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The metadata for a file.
#'
#' @param File.appProperties The \link{File.appProperties} object or list of objects
#' @param File.capabilities The \link{File.capabilities} object or list of objects
#' @param File.contentHints The \link{File.contentHints} object or list of objects
#' @param File.contentHints.thumbnail The \link{File.contentHints.thumbnail} object or list of objects
#' @param File.imageMediaMetadata The \link{File.imageMediaMetadata} object or list of objects
#' @param File.imageMediaMetadata.location The \link{File.imageMediaMetadata.location} object or list of objects
#' @param File.properties The \link{File.properties} object or list of objects
#' @param File.videoMediaMetadata The \link{File.videoMediaMetadata} object or list of objects
#' @param appProperties A collection of arbitrary key-value pairs which are private to the requesting app
#' @param capabilities Capabilities the current user has on this file
#' @param contentHints Additional information about the content of the file
#' @param copyRequiresWriterPermission Whether the options to copy, print, or download this file, should be disabled for readers and commenters
#' @param createdTime The time at which the file was created (RFC 3339 date-time)
#' @param description A short description of the file
#' @param explicitlyTrashed Whether the file has been explicitly trashed, as opposed to recursively trashed from a parent folder
#' @param fileExtension The final component of fullFileExtension
#' @param folderColorRgb The color for a folder as an RGB hex string
#' @param fullFileExtension The full file extension extracted from the name field
#' @param hasAugmentedPermissions Whether any users are granted file access directly on this file
#' @param hasThumbnail Whether this file has a thumbnail
#' @param headRevisionId The ID of the file's head revision
#' @param iconLink A static, unauthenticated link to the file's icon
#' @param id The ID of the file
#' @param imageMediaMetadata Additional metadata about image media, if available
#' @param isAppAuthorized Whether the file was created or opened by the requesting app
#' @param lastModifyingUser The last user to modify the file
#' @param md5Checksum The MD5 checksum for the content of the file
#' @param mimeType The MIME type of the file
#' @param modifiedByMe Whether the file has been modified by this user
#' @param modifiedByMeTime The last time the file was modified by the user (RFC 3339 date-time)
#' @param modifiedTime The last time the file was modified by anyone (RFC 3339 date-time)
#' @param name The name of the file
#' @param originalFilename The original filename of the uploaded content if available, or else the original value of the name field
#' @param ownedByMe Whether the user owns the file
#' @param owners The owners of the file
#' @param parents The IDs of the parent folders which contain the file
#' @param permissionIds List of permission IDs for users with access to this file
#' @param permissions The full list of permissions for the file
#' @param properties A collection of arbitrary key-value pairs which are visible to all apps
#' @param quotaBytesUsed The number of storage quota bytes used by the file
#' @param shared Whether the file has been shared
#' @param sharedWithMeTime The time at which the file was shared with the user, if applicable (RFC 3339 date-time)
#' @param sharingUser The user who shared the file with the requesting user, if applicable
#' @param size The size of the file's content in bytes
#' @param spaces The list of spaces which contain the file
#' @param starred Whether the user has starred the file
#' @param teamDriveId ID of the Team Drive the file resides in
#' @param thumbnailLink A short-lived link to the file's thumbnail, if available
#' @param thumbnailVersion The thumbnail version for use in thumbnail cache invalidation
#' @param trashed Whether the file has been trashed, either explicitly or from a trashed parent folder
#' @param trashedTime The time that the item was trashed (RFC 3339 date-time)
#' @param trashingUser If the file has been explicitly trashed, the user who trashed it
#' @param version A monotonically increasing version number for the file
#' @param videoMediaMetadata Additional metadata about video media
#' @param viewedByMe Whether the file has been viewed by this user
#' @param viewedByMeTime The last time the file was viewed by the user (RFC 3339 date-time)
#' @param viewersCanCopyContent Deprecated - use copyRequiresWriterPermission instead
#' @param webContentLink A link for downloading the content of the file in a browser
#' @param webViewLink A link for opening the file in a relevant Google editor or viewer in a browser
#' @param writersCanShare Whether users with only writer permission can modify the file's permissions
#'
#' @return File object
#'
#' @family File functions
#' @export
File <- function(File.appProperties = NULL, File.capabilities = NULL, File.contentHints = NULL,
    File.contentHints.thumbnail = NULL, File.imageMediaMetadata = NULL, File.imageMediaMetadata.location = NULL,
    File.properties = NULL, File.videoMediaMetadata = NULL, appProperties = NULL,
    capabilities = NULL, contentHints = NULL, copyRequiresWriterPermission = NULL,
    createdTime = NULL, description = NULL, explicitlyTrashed = NULL, fileExtension = NULL,
    folderColorRgb = NULL, fullFileExtension = NULL, hasAugmentedPermissions = NULL,
    hasThumbnail = NULL, headRevisionId = NULL, iconLink = NULL, id = NULL, imageMediaMetadata = NULL,
    isAppAuthorized = NULL, lastModifyingUser = NULL, md5Checksum = NULL, mimeType = NULL,
    modifiedByMe = NULL, modifiedByMeTime = NULL, modifiedTime = NULL, name = NULL,
    originalFilename = NULL, ownedByMe = NULL, owners = NULL, parents = NULL, permissionIds = NULL,
    permissions = NULL, properties = NULL, quotaBytesUsed = NULL, shared = NULL,
    sharedWithMeTime = NULL, sharingUser = NULL, size = NULL, spaces = NULL, starred = NULL,
    teamDriveId = NULL, thumbnailLink = NULL, thumbnailVersion = NULL, trashed = NULL,
    trashedTime = NULL, trashingUser = NULL, version = NULL, videoMediaMetadata = NULL,
    viewedByMe = NULL, viewedByMeTime = NULL, viewersCanCopyContent = NULL, webContentLink = NULL,
    webViewLink = NULL, writersCanShare = NULL) {
    structure(list(File.appProperties = File.appProperties, File.capabilities = File.capabilities,
        File.contentHints = File.contentHints, File.contentHints.thumbnail = File.contentHints.thumbnail,
        File.imageMediaMetadata = File.imageMediaMetadata, File.imageMediaMetadata.location = File.imageMediaMetadata.location,
        File.properties = File.properties, File.videoMediaMetadata = File.videoMediaMetadata,
        appProperties = appProperties, capabilities = capabilities, contentHints = contentHints,
        copyRequiresWriterPermission = copyRequiresWriterPermission, createdTime = createdTime,
        description = description, explicitlyTrashed = explicitlyTrashed, fileExtension = fileExtension,
        folderColorRgb = folderColorRgb, fullFileExtension = fullFileExtension, hasAugmentedPermissions = hasAugmentedPermissions,
        hasThumbnail = hasThumbnail, headRevisionId = headRevisionId, iconLink = iconLink,
        id = id, imageMediaMetadata = imageMediaMetadata, isAppAuthorized = isAppAuthorized,
        kind = `drive#file`, lastModifyingUser = lastModifyingUser, md5Checksum = md5Checksum,
        mimeType = mimeType, modifiedByMe = modifiedByMe, modifiedByMeTime = modifiedByMeTime,
        modifiedTime = modifiedTime, name = name, originalFilename = originalFilename,
        ownedByMe = ownedByMe, owners = owners, parents = parents, permissionIds = permissionIds,
        permissions = permissions, properties = properties, quotaBytesUsed = quotaBytesUsed,
        shared = shared, sharedWithMeTime = sharedWithMeTime, sharingUser = sharingUser,
        size = size, spaces = spaces, starred = starred, teamDriveId = teamDriveId,
        thumbnailLink = thumbnailLink, thumbnailVersion = thumbnailVersion, trashed = trashed,
        trashedTime = trashedTime, trashingUser = trashingUser, version = version,
        videoMediaMetadata = videoMediaMetadata, viewedByMe = viewedByMe, viewedByMeTime = viewedByMeTime,
        viewersCanCopyContent = viewersCanCopyContent, webContentLink = webContentLink,
        webViewLink = webViewLink, writersCanShare = writersCanShare), class = "gar_File")
}

#' File.appProperties Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A collection of arbitrary key-value pairs which are private to the requesting app.Entries with null values are cleared in update and copy requests.
#'
#'
#'
#' @return File.appProperties object
#'
#' @family File functions
#' @export
File.appProperties <- function() {
    list()
}

#' File.capabilities Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Capabilities the current user has on this file. Each capability corresponds to a fine-grained action that a user may take.
#'
#' @param canAddChildren Whether the current user can add children to this folder
#' @param canChangeCopyRequiresWriterPermission Whether the current user can change the copyRequiresWriterPermission restriction of this file
#' @param canChangeViewersCanCopyContent Deprecated
#' @param canComment Whether the current user can comment on this file
#' @param canCopy Whether the current user can copy this file
#' @param canDelete Whether the current user can delete this file
#' @param canDownload Whether the current user can download this file
#' @param canEdit Whether the current user can edit this file
#' @param canListChildren Whether the current user can list the children of this folder
#' @param canMoveItemIntoTeamDrive Whether the current user can move this item into a Team Drive
#' @param canMoveTeamDriveItem Whether the current user can move this Team Drive item by changing its parent
#' @param canReadRevisions Whether the current user can read the revisions resource of this file
#' @param canReadTeamDrive Whether the current user can read the Team Drive to which this file belongs
#' @param canRemoveChildren Whether the current user can remove children from this folder
#' @param canRename Whether the current user can rename this file
#' @param canShare Whether the current user can modify the sharing settings for this file
#' @param canTrash Whether the current user can move this file to trash
#' @param canUntrash Whether the current user can restore this file from trash
#'
#' @return File.capabilities object
#'
#' @family File functions
#' @export
File.capabilities <- function(canAddChildren = NULL, canChangeCopyRequiresWriterPermission = NULL,
    canChangeViewersCanCopyContent = NULL, canComment = NULL, canCopy = NULL, canDelete = NULL,
    canDownload = NULL, canEdit = NULL, canListChildren = NULL, canMoveItemIntoTeamDrive = NULL,
    canMoveTeamDriveItem = NULL, canReadRevisions = NULL, canReadTeamDrive = NULL,
    canRemoveChildren = NULL, canRename = NULL, canShare = NULL, canTrash = NULL,
    canUntrash = NULL) {
    structure(list(canAddChildren = canAddChildren, canChangeCopyRequiresWriterPermission = canChangeCopyRequiresWriterPermission,
        canChangeViewersCanCopyContent = canChangeViewersCanCopyContent, canComment = canComment,
        canCopy = canCopy, canDelete = canDelete, canDownload = canDownload, canEdit = canEdit,
        canListChildren = canListChildren, canMoveItemIntoTeamDrive = canMoveItemIntoTeamDrive,
        canMoveTeamDriveItem = canMoveTeamDriveItem, canReadRevisions = canReadRevisions,
        canReadTeamDrive = canReadTeamDrive, canRemoveChildren = canRemoveChildren,
        canRename = canRename, canShare = canShare, canTrash = canTrash, canUntrash = canUntrash),
        class = "gar_File.capabilities")
}


#' File.properties Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A collection of arbitrary key-value pairs which are visible to all apps.Entries with null values are cleared in update and copy requests.
#'
#'
#'
#' @return File.properties object
#'
#' @family File functions
#' @export
File.properties <- function() {
    list()
}

